//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLoader.DataManagement {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataManagement.IDataManager")]
    public interface IDataManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataManager/LoadLabels", ReplyAction="http://tempuri.org/IDataManager/LoadLabelsResponse")]
        void LoadLabels(System.Collections.Generic.Dictionary<string, string> labels);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataManager/LoadLabels", ReplyAction="http://tempuri.org/IDataManager/LoadLabelsResponse")]
        System.Threading.Tasks.Task LoadLabelsAsync(System.Collections.Generic.Dictionary<string, string> labels);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataManager/LoadAdjancentNodes", ReplyAction="http://tempuri.org/IDataManager/LoadAdjancentNodesResponse")]
        void LoadAdjancentNodes(string nodeId, string[] adjancentNodes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataManager/LoadAdjancentNodes", ReplyAction="http://tempuri.org/IDataManager/LoadAdjancentNodesResponse")]
        System.Threading.Tasks.Task LoadAdjancentNodesAsync(string nodeId, string[] adjancentNodes);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataManagerChannel : DataLoader.DataManagement.IDataManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataManagerClient : System.ServiceModel.ClientBase<DataLoader.DataManagement.IDataManager>, DataLoader.DataManagement.IDataManager {
        
        public DataManagerClient() {
        }
        
        public DataManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void LoadLabels(System.Collections.Generic.Dictionary<string, string> labels) {
            base.Channel.LoadLabels(labels);
        }
        
        public System.Threading.Tasks.Task LoadLabelsAsync(System.Collections.Generic.Dictionary<string, string> labels) {
            return base.Channel.LoadLabelsAsync(labels);
        }
        
        public void LoadAdjancentNodes(string nodeId, string[] adjancentNodes) {
            base.Channel.LoadAdjancentNodes(nodeId, adjancentNodes);
        }
        
        public System.Threading.Tasks.Task LoadAdjancentNodesAsync(string nodeId, string[] adjancentNodes) {
            return base.Channel.LoadAdjancentNodesAsync(nodeId, adjancentNodes);
        }
    }
}
